package com.alibaba.otter.canal.protocol.atlas.base;

public enum HookNotificationType {
  TYPE_CREATE,
  TYPE_UPDATE,
  ENTITY_CREATE,
  ENTITY_PARTIAL_UPDATE,
  ENTITY_FULL_UPDATE,
  ENTITY_DELETE,
  ENTITY_CREATE_V2,
  ENTITY_PARTIAL_UPDATE_V2,
  ENTITY_FULL_UPDATE_V2,
  ENTITY_DELETE_V2
}
